### ISSUE TITLE
只能添加一张图片，添加第二张的时候就报异常了

### ISSUE THREAD

**Issue by liulinsen** [KDF5000/RichEditText#3]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { dat=content://media/external/images/media/920 flg=0x1 }} to activity {com.linsen.leason.propertydemo/com.linsen.leason.propertydemo.richedit.EdittextActivity}: java.lang.IndexOutOfBoundsException: replace (71 ... 71) ends beyond length 68

**Comment by KDF5000** [comment]
这个项目是两年前做毕设写的，我这现在没有开发环境，从你发的错误信息应该是EdittextActivity里的replace函数访问数组越界了，你可以检查一下吗？非常抱歉

**Comment by KDF5000** [comment]
@liulinsen 你可以先试试里面那个example添加第二张图片的时候有没有异常

**Comment by liulinsen** [comment]
我今天试了下，如果添加图片后接着添加图片是没有问题的，但如果输了文字或空格之类的内容，再添加就会报这个错

**Comment by KDF5000** [comment]
@liulinsen 那个问题解决了吗？昨天修改了一下代码，你可以试试
